// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQAY6q_PeDD4-NihdpX9fqXYgcxgjRwf4',
    appId: '1:464211923494:web:1f79693392385a966d4ce7',
    messagingSenderId: '464211923494',
    projectId: 'lamaplayy',
    authDomain: 'lamaplayy.firebaseapp.com',
    storageBucket: 'lamaplayy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeyhuq--XhIChAUioEI4CcgfehrUPmWd8',
    appId: '1:464211923494:android:d54a2a64afd7fadb6d4ce7',
    messagingSenderId: '464211923494',
    projectId: 'lamaplayy',
    storageBucket: 'lamaplayy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD16kWSsJw7e1AFxdjKQF90wBh-e2PpAVQ',
    appId: '1:464211923494:ios:55f0c31f092fd2aa6d4ce7',
    messagingSenderId: '464211923494',
    projectId: 'lamaplayy',
    storageBucket: 'lamaplayy.firebasestorage.app',
    iosBundleId: 'com.example.lamaplay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD16kWSsJw7e1AFxdjKQF90wBh-e2PpAVQ',
    appId: '1:464211923494:ios:55f0c31f092fd2aa6d4ce7',
    messagingSenderId: '464211923494',
    projectId: 'lamaplayy',
    storageBucket: 'lamaplayy.firebasestorage.app',
    iosBundleId: 'com.example.lamaplay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQAY6q_PeDD4-NihdpX9fqXYgcxgjRwf4',
    appId: '1:464211923494:web:548137c5296f52d36d4ce7',
    messagingSenderId: '464211923494',
    projectId: 'lamaplayy',
    authDomain: 'lamaplayy.firebaseapp.com',
    storageBucket: 'lamaplayy.firebasestorage.app',
  );
}
